services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 12345 -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ExpensesTrackerApp/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      DB_HOST: "sqlserver"
      DB_PORT: "SQLEXPRESS"
      DB_NAME: "ExpensesDbApi"
      DB_USER: "Petros"
      DB_PASS: "12345"
      JWT_SECRET: "YXkZTQlhy98mWxbsA4iGx8mciGoXbz7cWhjTNV40="
    depends_on:
      sqlserver:
        condition: service_healthy